name: Build All Packages

on:
  workflow_dispatch:

jobs:
  build-merkle-memberships-plugin:
    uses: ./.github/workflows/reusable-npm-build.yaml
    with:
      package_name: 'minauth-merkle-memberships-plugin'
      package_path: './minauth-plugins/minauth-merkle-memberships-plugin'

